[package]
name = "nex-json"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
nex-parser = { path = "../nex-parser" }
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true